apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: {{ .Release.Name }}-frontend-ingress
  namespace: default
spec:
  hosts:
  - {{ printf "%s.spicynoodle.xyz" .Release.Name }}
  gateways:
  - spicynoodle-gateway
  http:
  - route:
    - destination:  
        host: {{ printf "frontend.%s.svc.cluster.local" .Release.Name }}
        port:
          number: 80

